name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 18
          cache: 'yarn'

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.access_token }}
          build_script_name: 'electron:prebuild'
          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
      
      - uses: actions/upload-artifact@v3
        with:
          name: zyplayer-mac
          path: dist_electron/*-universal.dmg
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v3
        with:
          name: zyplayer-win
          path: dist_electron/*Setup*.exe
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v3
        with:
          name: zyplayer-linux
          path: dist_electron/*.AppImage
          if-no-files-found: ignore